### ISSUE TITLE
styled-system hits error on IE11 - Object doesn't support property or method 'assign'

### ISSUE THREAD

**Issue by hebinhuang** [jxnblk/styled-system#278]
I hit error below when I run my web app on IE11, other browser (Chrome, Edge) works fine.

`Object doesn't support property or method 'assign'
TypeError: Object doesn't support property or method 'assign'
   at Anonymous function (node_modules/system-components/node_modules/styled-system/dist/util.js:62:0)
   at merge (node_modules/system-components/node_modules/styled-system/dist/util.js:59:0)
   at compose (node_modules/system-components/node_modules/styled-system/dist/util.js:77:0)
   at ../node_modules/system-components/node_modules/styled-system/dist/styles.js (node_modules/system-components/node_modules/styled-system/dist/styles.js:52:0)
   at __webpack_require__ (webpack:/webpack/bootstrap a2a886c73705cfa0ba27:714:0)
   at fn (webpack:/webpack/bootstrap a2a886c73705cfa0ba27:117:0)
   at ../node_modules/system-components/node_modules/styled-system/dist/index.js (node_modules/system-components/node_modules/styled-system/dist/index.js:33:0)
   at __webpack_require__ (webpack:/webpack/bootstrap a2a886c73705cfa0ba27:714:0)
   at fn (webpack:/webpack/bootstrap a2a886c73705cfa0ba27:117:0)
   at ../node_modules/system-components/dist/System.js (node_modules/system-components/dist/System.js:15:0)
`

**Comment by Avizura** [comment]
@hebinhuang could you say how you solved this issue?

**Comment by jtmthf** [comment]
@Avizura The fix was likely by using [zloirock/core-js](zloirock/core-js) in polyfill mode. Polyfills should be the first imports in your entry-chunk generally.

For core-js v2:

```js
import 'core-js/fn/object/assign';
```

For core-js v3:

```js
import 'core-js/features/object/assign';
```
